name: "yamllint action"
description: "Lint YAML files using [yamllint](https://github.com/adrienverge/yamllint)."
author: "Mitsuaki Wada"
inputs:
  yamllint_flags:
    description: "Flags to pass to yamllint"
    required: false
    default: ""
  only_changed:
    description: "Lint only changed(added/modified) files"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
    - name: Install yamllint
      shell: bash
      run: |
        pip install yamllint
    - name: Get changed files
      if: ${{ inputs.only_changed == 'true' && github.base_ref != null }}
      run: |
        git fetch --depth 1 origin ${{ github.base_ref }}

        CHANGED_FILES=$(
          comm -12 \
            <(git diff --diff-filter=d --name-only origin/${{ github.base_ref }} | sort || kill $$) \
            <(yamllint --list-files . | sed 's|^\./||' | sort || kill $$) \
            | tr '\n' ' '
        )
        echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV
      shell: bash
    - name: Lint YAML files
      shell: bash
      run: |
        readarray -t CHANGED_FILES < <(echo ${{ env.CHANGED_FILES }} | tr ' ' '\n')
        yamllint ${{ inputs.yamllint_flags }} "${CHANGED_FILES[@]}"
