name: "yamllint action"
description: "Lint YAML files using [yamllint](https://github.com/adrienverge/yamllint)."
author: "Mitsuaki Wada"
inputs:
  yamllint_flags:
    description: "Flags to pass to yamllint"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
    - name: Install yamllint
      shell: bash
      run: |
        pip install yamllint
    - name: Lint YAML files
      shell: bash
      run: |
        yamllint .
