name: Test
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML files
        uses: ./
        with:
          yamllint_flags: ./testdata
          level: info
          fail_level: none
  test_only_changed:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML files
        uses: ./
        with:
          only_changed: true
          level: info
          fail_level: none
  test_all_files:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML files
        uses: ./
        with:
          yamllint_flags: .
          level: info
          fail_level: none
